# Generated by Django 4.2.17 on 2024-12-08 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=255)),
                ('about', models.TextField()),
                ('org', models.CharField(max_length=200)),
                ('img_url', models.URLField(blank=True, max_length=500, null=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
